FROM debian:trixie-slim

LABEL version="slim"
LABEL description="NodeJS latest version with nvm based on Debian trixie-slim"
LABEL maintainer="robertgontarski"
LABEL source="https://github.com/robertgontarski/node-docker-image"
LABEL license="MIT"
LABEL type="languages and frameworks"

RUN apt update
RUN apt install -y \
    curl 

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
    export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
    nvm install node --default

RUN apt-get remove --purge -y curl && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /var/www

CMD [ "/bin/bash" ]